table dim_payment
	lineageTag: 56198358-1e5a-4cc5-8d39-62773e1e99c2

	column payment_id
		dataType: int64
		formatString: 0
		lineageTag: 9e1fe00f-2134-4c24-acee-aacdad39a581
		summarizeBy: none
		sourceColumn: payment_id

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: d3b72160-2ef7-4463-99d9-3286dce0948e
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	partition dim_payment = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\ecom\dim_payment.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"payment_id", Int64.Type}, {"payment_method", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

