table dim_customer
	lineageTag: 810fa6c7-a383-4ae0-b985-88e6bcad3a07

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 36ef3961-6638-44d3-89bc-acda4a0faaaf
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: dcb0cbf2-b945-4dae-8426-4a5c51004df9
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 00e838b9-7dc7-4954-ba89-d23b91482942
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column join_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c25a863f-6052-4bc4-9e05-13450da48bc6
		summarizeBy: none
		sourceColumn: join_date

		variation Variation
			isDefault
			relationship: 272dcf8b-ced2-4469-9c21-36632564dfd0
			defaultHierarchy: LocalDateTable_b195d493-36d9-4822-98e5-5bc7a208504c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column loyalty_tier
		dataType: string
		lineageTag: 73f21c45-6e72-4f46-8bed-4bdafa177536
		summarizeBy: none
		sourceColumn: loyalty_tier

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: cf5b3f22-39b8-471e-bb7a-cd7012a67bcf
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column 'Recency Days' = ```
			
			VAR LastOrderDate = 
			    CALCULATE(
			        MAX(fact_sales[order_date]),
			        RELATEDTABLE(fact_sales)
			    )
			VAR LatestDate = DATE(2025, 9, 26)  // Your dataset end date
			RETURN 
			    IF(
			        ISBLANK(LastOrderDate),
			        BLANK(),
			        DATEDIFF(LastOrderDate, LatestDate, DAY)
			    )
			```
		formatString: 0
		lineageTag: ec646a45-8a0b-4c2b-98ce-ca9206864473
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Frequency Orders' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_sales[order_id]),
			    RELATEDTABLE(fact_sales)
			)
		formatString: 0
		lineageTag: db67fb05-b750-4aac-a8e1-8fc79b86b54d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Monetary Value' =
			
			CALCULATE(
			    SUM(fact_sales[line_revenue]),
			    RELATEDTABLE(fact_sales)
			)
		lineageTag: 4272196d-5a61-415f-ac9e-74b12e160516
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RFM Segment' =
			
			VAR R = dim_customer[Recency Days]
			VAR F = dim_customer[Frequency Orders]
			RETURN
			    SWITCH(
			        TRUE(),
			        R <= 90 && F >= 5, "Champions",
			        R > 90 && R <= 180 && F >= 5, "At Risk ⚠️",
			        R <= 90 && F < 3, "New Customers",
			        R > 180, "Lost 🚨",
			        "Other"
			    )
		lineageTag: cde70e4b-1d83-4bf1-a9d2-60dd95741401
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Cohort Month' = ```
			
			VAR FirstPurchase = 
			    CALCULATE(
			        MIN(fact_sales[order_date]),
			        RELATEDTABLE(fact_sales)
			    )
			RETURN FORMAT(FirstPurchase, "YYYY-MM")
			```
		lineageTag: 411598ae-963a-494f-a10f-ade6e7c6136b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'LTV Bucket' =
			
			VAR LTV = dim_customer[Monetary Value]
			RETURN
			    SWITCH(
			        TRUE(),
			        LTV < 500, "$0-500",
			        LTV < 1000, "$501-1K",
			        LTV < 2000, "$1K-2K",
			        LTV < 5000, "$2K-5K",
			        LTV < 10000, "$5K-10K",
			        "$10K+"
			    )
		lineageTag: 5cf5c771-4a48-41cd-a717-b4dd16adb657
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\ecom\dim_customer.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_name", type text}, {"email", type text}, {"join_date", type date}, {"loyalty_tier", type text}, {"gender", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

